apiVersion: v2
name: augmented-networkpolicy-operator
description: A Helm chart for the Augmented NetworkPolicy Operator
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: ayoy
